//users

export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CURRENT_USER_FETCHED = 'CURRENT_USER_FETCHED';

//services

export const SERVICES_FETCHED = 'SERVICES_FETCHED';
export const SERVICE_SELECTED = 'SERVICE_SELECTED';

//bookings

export const BOOKING_DELETED = 'BOOKING_DELETED';
export const BOOKING_CREATED = 'BOOKING_CREATED';
export const BOOKINGS_FETCHED = 'BOOKINGS_FETCHED';
export const BOOKING_UPDATED = 'BOOKING_UPDATED';

//quotes

export const QUOTES_FETCHED = 'QUOTES_FETCHED';
export const QUOTE_UPDATED = 'QUOTE_UPDATED';
export const QUOTE_DELETED = 'QUOTE_DELETED';
export const QUOTE_CREATED = 'QUOTE_CREATED';

//ticket
export const TICKET_CREATED = 'TICKET_CREATED';
export const TICKETS_FETCHED = 'TICKETS_FETCHED';
export const TICKET_UPDATED = 'TICKET_UPDATED';
export const TICKET_DELETED = 'TICKET_DELETED';

// users resources

export const USERS_FETCHED = 'USERS_FETCHED';
export const USER_UPDATED = 'USER_UPDATED';
export const USER_DELETED = 'USER_DELETED';

//form options
export const STAFF_OPTIONS_FETCHED = 'STAFF_OPTIONS_FETCHED';
export const PAYMENT_OPTIONS_FETCHED = 'PAYMENT_OPTIONS_FETCHED';
export const JOB_STATUS_OPTIONS_FETCHED = 'JOB_STATUS_OPTIONS_FETCHED';
